; PlatformIO project configuration
; Antenna Tracker for RC Planes – ESP32 + MAVLink + QMC5883L + MPU6050

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    madhephaestus/ESP32Servo @ ^0.11.0
